config/routes.rb
Twfynz::Application.routes.draw do
  root :to => "application#home"
  match "search" => "application#search"
  match "about" => "application#about"

  resources :bills do
    collection do
      get "assented"
      get "negatived"
    end
  end
  resources :portfolios
  resources :mps do
    collection do
      get "by_first"
      get "by_party"
      get "by_electorate"
      get "contribution_match"
    end
  end

  resources :organisations
  resources :parliaments
  resources :submissions
  resources :trackings
  resources :places, only: :index do
    get ':name' => 'places#show_place', on: :collection
  end

  match "portfolios/:portfolio_url/:year/:month/:day/:url_slug" => "debates#show_portfolio_debate", :as => "show_portfolio_debate"

  resources :debates do
    collection do
      get ":date", to: "debates#show_debates_on_date", as: "on_date"
    end
  end
  resources :parties
  resources :written_questions do
    collection do
      get "by_asker"
      get "by_portfolio"
    end
  end

  match 'users/signup' => 'user#signup', via: [:get, :post]
  post 'users/signup/individual' => 'user#signup_individual'
  post 'users/signup/organisation' => 'user#signup_organisation'
  post 'users/login' => 'user#login'
  get 'users/logout' => 'user#logout'
  get 'users/forgot_password' => 'user#forgot_password'
  get 'users/change_password' => 'user#change_password'
  get 'user/:user_name' => 'user#user_home'

end

app/models/party.rb
# encoding: UTF-8
# == Schema Information
#
# Table name: parties
#
#  id            :integer          not null, primary key
#  short         :string(255)      not null
#  name          :string(255)
#  vote_name     :string(255)
#  registered    :date
#  abbreviation  :string(255)
#  url           :string(255)
#  colour        :string(6)
#  logo          :string(255)
#  wikipedia_url :string(255)
#

require 'acts_as_wikipedia'

class Party < ActiveRecord::Base
  acts_as_wikipedia

  has_many :parliament_parties
  has_many :mps, :foreign_key => 'member_of_id'
  has_many :members

  has_many :donations

  has_many :vote_casts
  has_many :votes, :through => :vote_casts, :include => {:contribution => :spoken_in}

  class << self
    def act; @act ||= from_vote_name("ACT New Zealand"); end
    def green; @green ||= from_vote_name("Green Party"); end
    def labour; @labour ||= from_vote_name("New Zealand Labour"); end
    def maori; @maori ||= from_vote_name("Māori Party"); end
    def national; @national ||= from_vote_name("New Zealand National"); end
    def nz_first; @nz_first ||= from_vote_name("New Zealand First"); end
    def progressive; @progressive ||= from_vote_name("Progressive"); end
    def united_future; @united_future ||= from_vote_name("United Future"); end
    def mana; @mana ||= from_vote_name("Mana"); end

    def party_list
      [act, green, labour, maori, national, nz_first, progressive, united_future]
    end

    def party_matrix
      act = Party.act
      green = Party.green
      labour = Party.labour
      maori = Party.maori
      national = Party.national
      nz_first = Party.nz_first
      progressive = Party.progressive
      united_future = Party.united_future
      independent = from_vote_name "Independent"

      matrix = [
[	[labour , labour, 0, {}], 	[labour , national, 0, {}], 	[labour , green, 0, {}], 	[labour , nz_first, 0, {}], 	[labour , maori, 0, {}], 	[labour , act, 0, {}], 	[labour , united_future, 0, {}], 	[labour , progressive, 0, {}] 	],
[	[progressive, labour, 0, {}], 	[progressive, national, 0, {}], 	[progressive, green, 0, {}], 	[progressive, nz_first, 0, {}], 	[progressive, maori, 0, {}], 	[progressive, act, 0, {}], 	[progressive, united_future, 0, {}], 	[progressive, progressive, 0, {}] 	],
[	[nz_first, labour, 0, {}], 	[nz_first, national, 0, {}], 	[nz_first, green, 0, {}], 	[nz_first, nz_first, 0, {}], 	[nz_first, maori, 0, {}], 	[nz_first, act, 0, {}], 	[nz_first, united_future, 0, {}], 	[nz_first, progressive, 0, {}] 	],
[	[united_future, labour, 0, {}], 	[united_future, national, 0, {}], 	[united_future, green, 0, {}], 	[united_future, nz_first, 0, {}], 	[united_future, maori, 0, {}], 	[united_future, act, 0, {}], 	[united_future, united_future, 0, {}], 	[united_future, progressive, 0, {}] 	],
[	[green , labour, 0, {}], 	[green , national, 0, {}], 	[green , green, 0, {}], 	[green , nz_first, 0, {}], 	[green , maori, 0, {}], 	[green , act, 0, {}], 	[green , united_future, 0, {}], 	[green , progressive, 0, {}] 	],
[	[maori , labour, 0, {}], 	[maori , national, 0, {}], 	[maori , green, 0, {}], 	[maori , nz_first, 0, {}], 	[maori , maori, 0, {}], 	[maori , act, 0, {}], 	[maori , united_future, 0, {}], 	[maori , progressive, 0, {}] 	],
[	[national, labour, 0, {}], 	[national, national, 0, {}], 	[national, green, 0, {}], 	[national, nz_first, 0, {}], 	[national, maori, 0, {}], 	[national, act, 0, {}], 	[national, united_future, 0, {}], 	[national, progressive, 0, {}] 	],
[	[act , labour, 0, {}], 	[act , national, 0, {}], 	[act , green, 0, {}], 	[act , nz_first, 0, {}], 	[act , maori, 0, {}], 	[act , act, 0, {}], 	[act , united_future, 0, {}], 	[act , progressive, 0, {}] 	]
      ]
    end

    def from_vote_name name
      party = find_by_vote_name(name)
      party = find_by_short(name) unless party
      party
    end

    def all_size_ordered
      latest_id = Parliament.latest.id
      find(:all, :include => :mps).select{|p| p.mps.size > 0}.sort_by {|p| p.mp_count(latest_id) }.reverse
    end

    def get_party name
      find(:all, :include => {:mps=>:bills}).select {|p| p.id_name == name}.first
    end

    def find_all_sorted
      find(:all).sort{|a,b| b.mp_count <=> a.mp_count}
    end

    def mp_count
      find_all_sorted.collect do |party|
        [party.short, party.mp_count]
      end
    end

    def colours
      find_all_sorted.collect {|p| '#'+p.colour}
    end
  end

  def display_name
    if short == 'Green'
      'The Green Party'
    elsif short == 'Maori Party'
      'The Māori Party'
    else
      short
    end
  end

  def member_count_on_date date
    @member_count_on_date ||= members.select {|m| m.is_active_on(date)}.size
    @member_count_on_date
  end

  def bill_third_reading_and_negatived_votes parliament_number
    third_reading_and_negatived = Vote.third_reading_and_negatived_votes(parliament_number)
    @bill_third_reading_and_negatived_votes ||= Set.new(party_votes(parliament_number)).&(third_reading_and_negatived).to_a
    @bill_third_reading_and_negatived_votes
  end

  def split_bill_third_reading_and_negatived_votes parliament_number
    votes = bill_third_reading_and_negatived_votes(parliament_number)
    votes.select {|p| p.noes_by_party[1].key?(self) && p.ayes_by_party[1].key?(self)}
  end

  def party_votes parliament_number
    @party_votes ||= Vote.remove_duplicates( votes ).select{|v| Parliament.date_within?(parliament_number, v.debate.date)}
    @party_votes
  end

  def split_party_votes parliament_number
    party_votes(parliament_number).select {|p| p.noes_by_party[1].key?(self) && p.ayes_by_party[1].key?(self)}
  end

  def compare_with other, another
    ayes, noes, abstentions = third_reading_ayes_noes_abstentions
    other_ayes, other_noes, other_abstentions = other.third_reading_ayes_noes_abstentions
    another_ayes, another_noes, another_abstentions = another.third_reading_ayes_noes_abstentions

    only_ayes = ayes - other_ayes - another_ayes
    only_noes = noes - other_noes - another_noes
    only_abstentions = abstentions - other_abstentions - another_abstentions

    ayes_with_other = (ayes - only_ayes) - another_ayes
    noes_with_other = (noes - only_noes) - another_noes
    abstentions_with_other = (abstentions - only_abstentions) - another_abstentions

    ayes_with_another = (ayes - only_ayes) - other_ayes
    noes_with_another = (noes - only_noes) - other_noes
    abstentions_with_another = (abstentions - only_abstentions) - other_abstentions

    ayes_with_both = (ayes - only_ayes - ayes_with_other - ayes_with_another)
    noes_with_both = (noes - only_noes - noes_with_other - noes_with_another)
    abstentions_with_both = (abstentions - only_abstentions - abstentions_with_other - abstentions_with_another)

    only = (only_ayes + only_noes + only_abstentions)
    with_other = (ayes_with_other + noes_with_other + abstentions_with_other)
    with_another = (ayes_with_another + noes_with_another + abstentions_with_another)
    with_both = (ayes_with_both + noes_with_both + abstentions_with_both)
    return [only, with_other, with_another, with_both]
  end

  def in_parliament number
    parliament_parties.select {|p| p.parliament_id == number}.first
  end

  def third_reading_ayes_noes_abstentions
    votes = PartyVote.third_reading_votes
    ayes = votes.select        {|p| p.ayes_by_party[0].include?(self)}
    noes = votes.select        {|p| p.noes_by_party[0].include?(self)}
    abstentions = votes.select {|p| p.abstentions_by_party[0].include?(self)}
    return [ayes, noes, abstentions]
  end

  def aye_votes_together other_party
    votes_together other_party, :ayes
  end

  def noe_votes_together other_party
    votes_together other_party, :noes
  end

  def votes_together other_party, cast
    third_reading_matrix = Vote.third_reading_matrix(cast)
    votes_together = nil

    third_reading_matrix.each do |row|
      cell = row.rassoc(self)
      if cell[0] == other_party
        votes_together = cell[3]
        break
      end
    end
    votes_together.keys.sort_by(&:bill_name)
  end

  def votes_comparison other_party, parliament_number
    votes = Vote.third_reading_and_negatived_votes(parliament_number)

    ayes_ayes = []
    noes_noes = []
    abstentions_abstentions = []
    novote_novote = []
    bothways_bothways = []

    ayes_noes = []
    noes_ayes = []

    ayes_abstentions = []
    noes_abstentions = []

    ayes_novote = []
    noes_novote = []

    ayes_bothways = []
    noes_bothways = []

    abstentions_ayes = []
    abstentions_noes = []
    abstentions_novote = []
    abstentions_bothways = []

    novote_ayes = []
    novote_noes = []
    novote_abstentions = []
    novote_bothways = []

    bothways_ayes = []
    bothways_noes = []
    bothways_abstentions = []
    bothways_novote = []

    votes.each do |vote|
      ayes = vote.ayes_cast_by_party
      noes = vote.noes_cast_by_party
      abstentions = vote.abstentions_cast_by_party

      if (ayes.key?(self) && noes.key?(self)) && (ayes.key?(other_party) && noes.key?(other_party))
        bothways_bothways << vote
      elsif (ayes.key?(self) && noes.key?(self)) && ayes.key?(other_party)
        bothways_ayes << vote
      elsif ayes.key?(self) && (ayes.key?(other_party) && noes.key?(other_party))
        ayes_bothways << vote
      elsif (ayes.key?(self) && noes.key?(self)) && noes.key?(other_party)
        bothways_noes << vote
      elsif noes.key?(self) && (ayes.key?(other_party) && noes.key?(other_party))
        noes_bothways << vote
      elsif ayes.key?(self) && ayes.key?(other_party)
        ayes_ayes << vote
      elsif noes.key?(self) && noes.key?(other_party)
        noes_noes << vote
      elsif ayes.key?(self) && noes.key?(other_party)
        ayes_noes << vote
      elsif noes.key?(self) && ayes.key?(other_party)
        noes_ayes << vote
      elsif noes.key?(self) && noes.key?(other_party)
        noes_noes << vote

app/controllers/parties_controller.rb
#encoding: utf-8
class PartiesController < ApplicationController

  caches_action :index, :show_party, :third_reading_and_negatived_votes, :compare_parties

  layout "parties_layout"

  def index
    @parties = Party.all_size_ordered
    @title = "Parties in Aotearoa New Zealand's Parliament"
    @total_mps = @parties.inject(0) {|count, p| count + p.mp_count }
#    @total_mps_48 = @parties.inject(0) {|count, p| count + p.mp_count(48) }
#    @total_mps_49 = @parties.inject(0) {|count, p| count + p.mp_count(49) }
    @parliament = Parliament.latest
    # @third_reading_matrix = Vote.third_reading_matrix(@parliament.id)
  end

  def compare_parties
    params[:parliament_number] = Parliament.latest.id
    compare_parties_by_parliament
  end

  def compare_parties_by_parliament
    party_name = params[:name]
    other_party_name = params[:other_name]
    parliament_number = params[:parliament_number]

    @parliament = Parliament.find(parliament_number)
    @party = Party::get_party party_name
    @other_party = Party::get_party other_party_name
    if @party && @other_party && @parliament
      # @aye_votes_together = @party.aye_votes_together(@other_party)
      # @noe_votes_together = @party.noe_votes_together(@other_party)

      @aye_votes_together, @noe_votes_together, @ayes_noes, @noes_ayes, @abstentions_abstentions, @ayes_abstentions, @noes_abstentions, @abstentions_ayes, @abstentions_noes, @novote_novote, @ayes_novote, @noes_novote, @abstentions_novote, @novote_ayes, @novote_noes, @novote_abstentions, @bothways_bothways, @ayes_bothways, @noes_bothways, @abstentions_bothways, @novote_bothways, @bothways_ayes, @bothways_noes, @bothways_abstentions, @bothways_novote = @party.votes_comparison(@other_party, parliament_number)
      @voted_same_way_count = @aye_votes_together.size + @noe_votes_together.size + @abstentions_abstentions.size + @novote_novote.size + @bothways_bothways.size
      @voted_different_way_count = @ayes_noes.size + @noes_ayes.size + @ayes_abstentions.size + @noes_abstentions.size + @abstentions_ayes.size + @abstentions_noes.size + @ayes_novote.size + @noes_novote.size + @abstentions_novote.size + @novote_ayes.size + @novote_noes.size + @novote_abstentions.size + @ayes_bothways.size + @noes_bothways.size + @abstentions_bothways.size + @novote_bothways.size + @bothways_ayes.size + @bothways_noes.size + @bothways_abstentions.size + @bothways_novote.size
      @total_count = @voted_same_way_count + @voted_different_way_count
      @voted_same_way_percent = @voted_same_way_count / @total_count.to_f * 100
      @voted_different_way_percent = @voted_different_way_count / @total_count.to_f * 100
      render :template => 'parties/compare_parties'
    else
      redirect_to :controller=>'application', :action=>'home'
    end
  end

  def show_party
    party = Party::get_party params[:name]

    if party
      @name = party.name
      @bills_in_charge_of = party.bills_in_charge_of
      @total_party_votes_size = {}
      @party_votes_size = {}
      @party_vote_percent = {}
      @total_bill_votes_size = {}
      @bill_votes_size = {}
      @bill_vote_percent = {}
      @party = party

      set_data_for_parliament(48)
      set_data_for_parliament(49)
    else
      render(:template => 'parties/invalid_party', :status => 404)
    end
  end

  def set_data_for_parliament parliament_no=48
    parliament = Parliament.find(parliament_no)
    party_in_parliament = @party.in_parliament(parliament_no)

    if party_in_parliament
      @total_party_votes_size[parliament_no] = parliament.party_votes_count
      @party_votes_size[parliament_no] = party_in_parliament.party_votes_count
      if @party_votes_size[parliament_no].nil?
        raise @party.inspect
      end
      @party_vote_percent[parliament_no] = (@party_votes_size[parliament_no] * 100.0) / @total_party_votes_size[parliament_no]

      @total_bill_votes_size[parliament_no] = parliament.bill_final_reading_party_votes_count
      @bill_votes_size[parliament_no] = party_in_parliament.bill_final_reading_party_votes_count
      @bill_vote_percent[parliament_no] = (@bill_votes_size[parliament_no] * 100.0) / @total_bill_votes_size[parliament_no]
    else
      @party_votes_size[parliament_no] = 0
    end
  end

  def contribution_match
    @recent_contribution = Contribution.find(params[:id])
    render :partial => 'recent_contribution', :locals => {:expand => params[:expand]}
  end

  def third_reading_and_negatived_votes
    @title = 'Bill third reading and negatived votes data'
    text = []
    Parliament.find_each do |parliament|
      html = "<p><strong>#{parliament.ordinal} Parliament</strong> "
      html += " (#{format_date(parliament.commission_opening_date)} - "
      html += "#{parliament.dissolution_date ? format_date(parliament.dissolution_date) : format_date(Date.today)}"
      html += ")<ul class='linklist'>"
      html += "<li><a href='#{third_reading_and_negatived_votes_by_parliament_url(:id=>parliament.id, :format=>'csv')}'>#{parliament.ordinal} Parliament bill votes CSV</a></li>"
      html += "<li><a href='#{third_reading_and_negatived_votes_by_parliament_for_r_url(:id=>parliament.id, :format=>'csv')}'>#{parliament.ordinal} Parliament bill votes CSV formatted for R</a></li></ul></p>"
      text << html
    end
    render :text => "<h1>#{@title}</h1><p>#{text.join('</p><p>')}</p>", :layout => 'parties_layout'
    # redirect_to third_reading_and_negatived_votes_by_parliament_url(:id => Parliament.latest.id)
  end
end

app/views/parties/_bill_link.haml
%li= link_to_bill bill_link

app/views/parties/_party_summary.haml
- unless party_summary.nil?
  - party = party_summary
  %tr.party
    %td= party_logo_small party
    %td= link_to(party.name, party)
    %td.count= party.mp_count(:latest)

app/views/parties/_unscaled_vote_cell.haml
- vote_cell = unscaled_vote_cell
- percentage = vote_cell[2]
- opacity = percentage == 0 ? 100 : percentage
- party = vote_cell[0]
- other_party = vote_cell[1]
- colour = party.short == 'Maori Party' ? Color::RGB::Brown.html : party.colour
- colour = party.short == 'NZ First' ? Color::RGB::Black.lighten_by(90).html : colour
- if percentage == 0 && party != other_party
  - color = 'white'
- elsif opacity > 75
  - color = Color::RGB.from_html(colour).adjust_brightness(40).lighten_by(40).mix_with(Color::RGB::White, 100).html
- else
  - color = Color::RGB.from_html(colour).adjust_brightness(40).lighten_by(40).mix_with(Color::RGB::White, opacity).html

- if percentage == 0 && party == other_party
  %td{:style=>"margin-right: 0; width: 5em; background: #{color}; text-align: center"}
- else
  - if false
    - color = color.lighten_by(lighten).html # .from_percentage(color_percent, color_percent, color_percent).html
  - elsif false
    - color = color.darken_by(-1 * lighten).html
  %td{:style=>"margin-right: 0; width: 5.2em; background: #{color}; text-align: center;"}
    - text = number_to_percentage(percentage, :precision => 0)
    - url = show_party_url(:name => party.url_name)
    - if party != other_party
      - url += "/#{other_party.url_name}"
      - url += "/#{@parliament.id.to_s}" if @parliament
    - class_name = (percentage > 75 ? 'high_vote_correlation' : percentage > 50 ? 'moderate_vote_correlation' : percentage > 25 ? 'low_vote_correlation' : 'minimumal_vote_correlation')
    - desc = "#{party.display_name} and #{other_party.display_name} voted the same way on #{vote_cell[3].size} bills"
    = link_to text, url, :class => class_name, :title => desc, :id => "#{party.url_name}-#{other_party.url_name}"

app/views/parties/_vote_cell.haml
- percentage = vote_cell[2]
- opacity = percentage == 0 ? 100 : percentage
- party = vote_cell[0]
- other_party = vote_cell[1]
- colour = party.short == 'Maori Party' ? Color::RGB::Brown.html : party.colour
- colour = party.short == 'NZ First' ? Color::RGB::Black.lighten_by(90).html : colour
- if opacity > 75
  - color = Color::RGB.from_html(colour).adjust_brightness(40).lighten_by(40).mix_with(Color::RGB::White, 100).html
- else
  - color = Color::RGB.from_html(colour).adjust_brightness(40).lighten_by(40).mix_with(Color::RGB::White, opacity).html

- width = 20 * polls[other_party]
- if percentage == 0
  %td{:style=>"margin-right: 0; width: #{width}em; background: #{color}; text-align: center"}
- else
  - if false
    - color = color.lighten_by(lighten).html # .from_percentage(color_percent, color_percent, color_percent).html
  - elsif false
    - color = color.darken_by(-1 * lighten).html
  - fontsize = [1 * polls[party] * 6.5, 1, 1 * polls[other_party] * 4.5].min
  %td{:style=>"margin-right: 0; width: #{width}em; background: #{color}; text-align: center; font-size:#{fontsize}em;"}
    - text = number_to_percentage(percentage, :precision => 0)
    - url = show_party_url(:name => party.url_name)
    - url += '/'+other_party.url_name if party != other_party
    - class_name = (percentage > 75 ? 'high_vote_correlation' : percentage > 50 ? 'moderate_vote_correlation' : percentage > 25 ? 'low_vote_correlation' : 'minimumal_vote_correlation')
    - desc = "#{party.display_name} and #{other_party.display_name} voted the same way on #{vote_cell[3].size} bills"
    = link_to text, url, :class => class_name, :title => desc

app/views/parties/compare_parties.haml
- @title = %Q[#{@party.display_name} vs #{@other_party.display_name}: #{@parliament.ordinal} New Zealand Parliament]
- @description = %Q[Comaparison of bill voting by #{@party.display_name} and #{@other_party.display_name} in the #{@parliament.ordinal} New Zealand Parliament]
#normalcontent
  %h1
    = @party.display_name
    and
    = @other_party.display_name
    compared
  %p
    In the
    = @parliament.ordinal
    Parliament:
  - unless @voted_same_way_count == 0
    %p.tab
      = @party.display_name
      and
      = @other_party.display_name
      voted in the
      = link_to("same way on #{number_to_percentage(@voted_same_way_percent, :precision=>0)}", '#voted_same_way')
      of final bill readings
      = " (#{@voted_same_way_count} out of #{@total_count})"
  - unless @voted_different_way_count == 0
    %p.tab
      = @party.display_name
      and
      = @other_party.display_name
      voted in a
      = link_to("different way on #{number_to_percentage(@voted_different_way_percent, :precision=>0)}", '#voted_different_way')
      of final bill readings
      = " (#{@voted_different_way_count} out of #{@total_count})"
  .divider3
  %p
    Bolded bill links below represent bills that passed their third reading.
    See other
    = link_to("parties compared", parliament_url(:id => @parliament.id)) + '.'
  - unless @voted_same_way_count == 0
    .divider3
    %h2#voted_same_way
      = "Voted in same way on #{@voted_same_way_count} final bill readings"
    = render :partial => 'bill_votes', :locals => {:party_vote=>'aye', :other_party_vote=>'aye', :party_vote2=>'no', :other_party_vote2=>'no', :votes=>@aye_votes_together, :votes2=>@noe_votes_together}
    - if @abstentions_abstentions.size > 0 || @novote_novote.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'abstention', :other_party_vote=>'abstention', :party_vote2=>'no vote', :other_party_vote2=>'no vote', :votes=>@abstentions_abstentions, :votes2=>@novote_novote}
    - if @bothways_bothways.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'bothways', :other_party_vote=>'bothways', :party_vote2=>'', :other_party_vote2=>'', :votes=>@bothways_bothways, :votes2=> nil}
  - unless @voted_different_way_count == 0
    .divider3
    %h2#voted_different_way
      = "Voted in a different way on #{@voted_different_way_count} final bill readings"
    - if @ayes_noes.size > 0 || @noes_ayes.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'aye', :other_party_vote=>'no', :party_vote2=>'no', :other_party_vote2=>'aye', :votes=>@ayes_noes, :votes2=>@noes_ayes}
    - if @ayes_abstentions.size > 0 || @noes_abstentions.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'aye', :other_party_vote=>'abstention', :party_vote2=>'no', :other_party_vote2=>'abstention', :votes=>@ayes_abstentions, :votes2=>@noes_abstentions}
    - if @abstentions_ayes.size > 0 || @abstentions_noes.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'abstention', :other_party_vote=>'aye', :party_vote2=>'abstention', :other_party_vote2=>'no', :votes=>@abstentions_ayes, :votes2=>@abstentions_noes}
    - if @ayes_bothways.size > 0 || @noes_bothways.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'aye', :other_party_vote=>'both aye and no', :party_vote2=>'no', :other_party_vote2=>'both aye and no', :votes=>@ayes_bothways, :votes2=>@noes_bothways}
    - if @bothways_ayes.size > 0 || @bothways_noes.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'both aye and no', :other_party_vote=>'aye', :party_vote2=>'both aye and no', :other_party_vote2=>'no', :votes=>@bothways_ayes, :votes2=>@bothways_noes}
    - if @ayes_novote.size > 0 || @noes_novote.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'aye', :other_party_vote=>'no vote', :party_vote2=>'no', :other_party_vote2=>'no vote', :votes=>@ayes_novote, :votes2=>@noes_novote}
    - if @novote_ayes.size > 0 || @novote_noes.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'no vote', :other_party_vote=>'aye', :party_vote2=>'no vote', :other_party_vote2=>'no', :votes=>@novote_ayes, :votes2=>@novote_noes}
    - if @bothways_novote.size > 0 || @novote_bothways.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'both aye and no', :other_party_vote=>'no vote', :party_vote2=>'no vote', :other_party_vote2=>'both aye and no', :votes=>@bothways_novote, :votes2=>@novote_bothways}
    - if @abstentions_bothways.size > 0 || @bothways_abstentions.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'abstention', :other_party_vote=>'both aye and no', :party_vote2=>'both aye and no', :other_party_vote2=>'abstention', :votes=>@abstentions_bothways, :votes2=>@bothways_abstentions}
    - if @abstentions_novote.size > 0 || @novote_abstentions.size > 0
      = render :partial => 'bill_votes', :locals => {:party_vote=>'abstention', :other_party_vote=>'no vote', :party_vote2=>'no vote', :other_party_vote2=>'abstention', :votes=>@abstentions_novote, :votes2=>@novote_abstentions}
  %p
    See other
    = link_to("parties compared", parliament_url(:id => @parliament.id)) + '.'

app/views/parties/index.haml
#normalcontent
  %h1 Political Parties
  .contentarea
    %p#compare_parties
      = link_to 'Compare party voting', parliament_url(:id => @parliament.id)
      in the
      = @parliament.ordinal
      Parliament.
    %table
      %thead
        %th
        %th Party
        %th{:style=>'text-align:center;'} MPs in 50th Parliament
      %tbody
        =render(:partial => 'party_summary', :collection => @parties, :locals => {:total_mps => @total_mps})
        %tr
          %td
          %td &nbsp;
          %td
        %tr
          %td
          %td TOTAL MPS
          %td.count= @total_mps