config/routes.rb
Twfynz::Application.routes.draw do
  root :to => "application#home"
  match "search" => "application#search"
  match "about" => "application#about"

  resources :bills do
    collection do
      get "assented"
      get "negatived"
    end
  end
  resources :portfolios
  resources :mps do
    collection do
      get "by_first"
      get "by_party"
      get "by_electorate"
      get "contribution_match"
    end
  end

  resources :organisations
  resources :parliaments
  resources :submissions
  resources :trackings
  resources :places, only: :index do
    get ':name' => 'places#show_place', on: :collection
  end

  match "portfolios/:portfolio_url/:year/:month/:day/:url_slug" => "debates#show_portfolio_debate", :as => "show_portfolio_debate"

  resources :debates do
    collection do
      get ":date", to: "debates#show_debates_on_date", as: "on_date"
    end
  end
  resources :parties
  resources :written_questions do
    collection do
      get "by_asker"
      get "by_portfolio"
    end
  end

  match 'users/signup' => 'user#signup', via: [:get, :post]
  post 'users/signup/individual' => 'user#signup_individual'
  post 'users/signup/organisation' => 'user#signup_organisation'
  post 'users/login' => 'user#login'
  get 'users/logout' => 'user#logout'
  get 'users/forgot_password' => 'user#forgot_password'
  get 'users/change_password' => 'user#change_password'
  get 'user/:user_name' => 'user#user_home'

end

app/controllers/bills_controller.rb
#encoding: utf-8
class BillsController < ApplicationController

  caches_action :index, :negatived, :assented, :show_bill_atom, :show_bill

  layout "bills_layout", :except => 'show_bill_atom'

  before_filter :find_bill, :only => [:show_bill, :show_bill_atom]

  def index
    @bills_on = true
    @bills_current = Bill.find_all_current.sort_by(&:bill_name)
    # @bills_current_by_event = Bill.find_all_current.sort_by(&:last_event_name).in_groups_by(&:last_event_name)
    # @bills_with_debates = Bill.find_all_current.group_by &:url
    # @letter_to_bills = @bills_with_debates.keys.group_by {|b| b[0..0]}
    # View code:
    # %p= render(:partial => 'bill_group_link', :collection => @letter_to_bills.keys.sort, :locals => {:prefix => ''})
          # = render(:partial => 'bill_group', :collection => @letter_to_bills.keys.sort, :locals => {:letter_to_bills => @letter_to_bills, :bills => @bills_with_debates, :prefix => '', :first => @letter_to_bills.keys.sort[0]})
  end

  def negatived
    @bills_on = true
    @bills_negatived = Bill.find_all_negatived.group_by(&:url)
    @letter_to_negatived = @bills_negatived.keys.group_by {|b| b[0..0]}
  end

  def assented
    @bills_on = true
    assented_by_parliament = Bill.find_all_assented_by_parliament
    @letter_to_assented_by_parliament = []
    @bills_assented_by_parliament = assented_by_parliament.collect do |by_parliament|
      parliament = by_parliament[0]
      grouped_by_url = by_parliament[1].group_by(&:url)
      @letter_to_assented_by_parliament << [parliament, grouped_by_url.keys.group_by {|b| b[0..0]}]
      [parliament, grouped_by_url]
    end
    @parliaments = @bills_assented_by_parliament.collect{|x| x[0]}
  end

  def show_bill_submissions
    @bills_on = true
    name = params[:bill_url]

    @bill = Bill.find_by_url(name)
    @name_to_submissions = Submission.find_all_by_business_item(@bill).group_by do |submission|
      if submission.submitter
        submission.submitter.name
      else
        submission.submitter_name
      end
    end
  end

  def show_bill_format
    format.html { show_bill }
    format.atom { show_bill_atom }
  end

  def show_bill_atom
    params[:format] = 'atom'
    @bill_events = @bill.bill_events.sort_by(&:date).reverse
  end

  def show
    @bill = Bill.find(params[:id])
    @admin = admin?
    @bills_on = true
    @tracking = get_tracking @bill
    @trackings = Tracking.all_for_item(@bill, current_user)
    unless read_fragment(:action => 'show_bill' )
      @hash = params
      @submissions_count = Submission.count_by_business_item @bill
      @top_level_bill_events = @bill.top_level_bill_events
      @have_votes = @bill.have_votes?
      @missing_votes = @bill.is_missing_votes?

      # retrieve_news_stories
    end
  end

  def find_bill
    name = params[:bill_url]
    unless (@bill = get_bill(name))
      render(:template => 'bills/invalid_bill', :status => 404)
    end
  end

  protected

    def retrieve_news_stories
      @news_items = @bill.news_items
      @blog_items = @bill.blog_items
      misplaced = @blog_items.inject([]) {|list, x| list << x if x.publisher[/Stuff\.co\.nz|scoop\.co\.nz/] || x.url[/tvnz\.co\.nz/]; list }
      unless misplaced.empty?
        @news_items += misplaced
        @news_items = @news_items.sort_by {|x| Date.parse(x.published_date) }.reverse
        @blog_items -= misplaced
      end
      @govt_items = @blog_items.inject([]) {|list, x| list << x if x.url[/govt\.nz/]; list }
      if @govt_items.empty?
        @govt_items = nil
      else
        @blog_items -= @govt_items
      end
    end

    def get_bill name
      if read_fragment(:action => 'show_bill' )
        @bill = Bill.find_by_url(name)
      else
        @bill = Bill.find_by_url(name, :include => [:submission_dates,
            :member_in_charge, :referred_to_committee,
            :sub_debates, {:debate_topics => :debate}])
      end
    end

    def get_tracking bill
      tracking = Tracking.new
      tracking.item = bill

      if (user_tracking = Tracking.from_user_and_item(current_user, bill))
        tracking.tracking_on = user_tracking.tracking_on
      else
        tracking.tracking_on = false
      end
      tracking
    end
end

app/helpers/bills_helper.rb
# encoding: UTF-8
module BillsHelper

  def summissions_meta_description bill
    if bill.description.blank?
      "Submissions on the #{bill.full_name}"
    else
      description = bill.description.split('.').first
      description.gsub!(/^(This|The) bill/i, "The #{bill.full_name}")
      "Submissions on the #{bill.full_name}. #{description}."
    end
  end

  def bill_meta_description bill
    if bill.description.blank?
      bill.full_name
    else
      description = bill.description.split('.').first
      description.gsub!(/^(This|The) bill/i, "The #{bill.full_name}")
      "#{description}."
    end
  end

  def bill_event_description bill_event
    # "#{bill_event.bill.bill_name}-#{bill_event.name}"
    url = bill_event_url(bill_event)
    date = format_date(bill_event.date)
    event_name = bill_event.name
    case bill_event.source.class.name
      when 'SubDebate'
        bill_event_debate_description event_name, url, date, bill_event.source
      when 'NzlEvent'
        bill_event_nzl_event_description event_name, url, bill_event.source
      else
        bill_event_notification_description bill_event.bill.bill_name, event_name, date, url
    end
  end

  def bill_event_notification_description bill_name, event_name, date, url
    case event_name.downcase.sub(' ','_').to_sym
      when :introduction
        "<p>#{date}: The #{link_to bill_name, url} was introduced to parliament.</p>"
      when :submissions_due
      "<p>Public submissions are due by #{date} for the #{link_to bill_name, url}.</p>"
      when :first_reading, :second_reading, :third_reading
        "<p>#{date}: The #{link_to bill_name, url} had a #{event_name.downcase} debate.</p><p>More details will be available after Parliament publishes the debate transcript.</p>"
      when :sc_reports
        "<p>The select committee report due on #{date} for the #{link_to bill_name, url}.</p>"
      when :in_committee
        "<p>The select committee report due on #{date} for the #{link_to bill_name, url}.</p>"
      else
        "<p>#{link_to(event_name, url)} on #{date}.</p>"
    end
  end

  def bill_event_debate_description event_name, url, date, debate
    link_text = "#{event_name.downcase} debate on #{date}"
    "The bill's #{link_to(link_text, url)} has been published."
  end

  def bill_event_nzl_event_description event_name, url, nzl_event
    "The bill as #{link_to(event_name.sub('introduction','introduced'), url)} published at legislation.govt.nz."
  end

  def submission_alert bill
    if (bill.respond_to? :submission_dates and (bill.submission_dates.size > 0))
      submission_date = bill.submission_dates[0]
      if Date.today <= submission_date.date
        url = "http://www.parliament.nz/en-NZ/SC/SubmCalled#{submission_date.parliament_url}"
        details = submission_date.details.chomp('.')
        %Q[#{link_to(details, url)} (link to external Parliament website).]
      else
        ''
      end
    else
      ''
    end
  end

  def split_bill_details bill_event
    details = ''
    bill = bill_event.bill
    if bill.nzl_events
      events = bill.nzl_events.select {|e| e.version_stage == 'reported' || e.version_stage == 'wip version updated' }.sort_by(&:publication_date)
      if events.size > 0
        details = %Q[#{link_to('View the bill', events.last.link)} as reported from the #{events.last.version_committee} at the New Zealand Legislation website.]
      end
    end
    details
  end

  def committee_report_details bill_event
    details = ''
    bill = bill_event.bill
    if bill.was_reported_by_committee?
      details = %Q[The #{link_to_committee(bill.referred_to_committee)} reported on this bill.]
    end
    if bill.nzl_events
      events = bill.nzl_events.select {|e| e.version_stage == 'reported' || e.version_stage == 'wip version updated' }.sort_by(&:publication_date)
      if events.size > 0
        details += %Q[ #{link_to('View the bill', events.last.link)} as reported from the #{events.last.version_committee} at the New Zealand Legislation website.]
      end
    end
    details
  end

  def committee_details bill_event
    bill = bill_event.bill
    if bill.is_before_committee?
      %Q[The #{link_to_committee(bill.referred_to_committee)} is considering this bill.]
    end
  end

  def mp_in_charge bill
    %Q[#{link_to_mp(bill.member_in_charge)} #{is_was(bill)} the member in charge of this #{bill_type(bill).camelize}.]
  end

  def is_was bill
    bill.current? ? 'is' : 'was'
  end

  def debate_date date, debates
    if debates.nil?
      format_date date
    elsif debates.size == 1
      format_date debates.first.date
    else
      debate_dates debates
    end
  end

  def debate_dates debates
    debates.reverse.collect do |d|
      date = format_date(d.date)
      date += ' (resumed)' if (d.contributions.size > 0 and d.contributions.first.text.include? 'Debate resumed')
      link_to(date, get_url(d))
    end.join(',<br />')
  end

  def vote_question vote
    vote ? vote.question : ''
  end

  def vote_casts_summary cast, bill_event
    if bill_event.has_votes?
      if bill_event.votes.size == 1 && bill_event.votes.first.is_a?(PartyVote)
        vote = bill_event.votes.first
        cast_count = vote.send("#{cast}_count".to_sym)
        if cast_count == 0
          '-'
        else
          parties, vote_casts = vote.send("#{cast}_by_party".to_sym)
          casts = parties.collect {|p| '<small>'+vote_cast_by_party_text(p, vote_casts[p],use_short_name=true)+'</small>'}
          "#{cast.capitalize} #{cast_count}<br/> #{casts.join('<br/>')}"
        end
      else
        bill_event.votes.collect { |v| (v and v.send("#{cast}_count".to_sym) != 0) ? v.send("#{cast}_count".to_sym) : '-' }.join('<br /><br />')
      end
    else
      ''
    end
  end

  def vote_casts_summary cast, bill_event
    if bill_event.has_votes?
      if bill_event.votes.size == 1 && bill_event.votes.first.is_a?(PartyVote)
        vote = bill_event.votes.first
        cast_count = vote.send("#{cast}_count".to_sym)
        if cast_count == 0
          '-'
        else
          parties, vote_casts = vote.send("#{cast}_by_party".to_sym)
          casts = parties.collect {|p| '<small>'+vote_cast_by_party_text(p, vote_casts[p],use_short_name=true)+'</small>'}
          "#{cast.capitalize} #{cast_count}<br/> #{casts.join('<br/>')}"
        end
      else
        bill_event.votes.collect { |v| (v and v.send("#{cast}_count".to_sym) != 0) ? v.send("#{cast}_count".to_sym) : '-' }.join('<br /><br />')
      end
    else
      ''
    end
  end

  def vote_ayes bill_event
    vote_casts_summary 'ayes', bill_event
  end

  def vote_noes bill_event
    vote_casts_summary 'noes', bill_event
  end

  def vote_abstentions bill_event
    vote_casts_summary 'abstentions', bill_event
  end

  def strip_tags text
    text.gsub(/<[pi]>/, '').gsub(/<\/[pi]>/,'')
  end

  def motion_agreed_to? text
    strip_tags(text) == 'Motion agreed to.'
  end

  def introduction bill_event
    bill = bill_event.bill
    intro = mp_in_charge(bill)
    if bill.nzl_events
      events = bill.nzl_events.select {|e| e.version_stage == 'introduction'}.sort_by(&:publication_date)
      if events.size > 0
        intro += %Q[<br/><br/>#{link_to('View the bill', events.last.link)} at introduction at the NZ Legislation website.]
      end
    end
  end

  def make_atom_id_tag bill_event, part=nil
    "tag:theyworkforyou.co.nz,#{bill_event.date}:#{bill_event.bill.url}/#{part.to_s}#{bill_event.name.downcase.gsub(' ','_')}"
  end

  def bill_event_atom_id bill_event
    unless bill_event.source
      make_atom_id_tag bill_event, 'parliament/'
    else
      case bill_event.source
        when NzlEvent
          make_atom_id_tag bill_event, 'legislation/'
        when Debate, SubDebate
          get_url(bill_event.source)
        else
          make_atom_id_tag bill_event
      end
    end
  end

  def show_bill_uri bill
    show_bill_url(bill, :bill_url => bill.url).sub(/\d+\?bill_url=/,'')
  end

  def bill_event_url bill_event
    unless bill_event.source
      show_bill_uri bill_event.bill
    else
      case bill_event.source
        when NzlEvent
          bill_event.source.link
        when Debate, SubDebate
          get_url(bill_event.source)
        else
          bill_event.source.class.name
      end
    end
  end

  def bill_event_name bill_event
    debate_name bill_event.name, bill_event.debates
  end

  def bill_event_dates bill_event
    debate_date bill_event.date, bill_event.debates
  end

  def bill_event_result_summary bill_event
    if !bill_event.has_debates?
      case bill_event.name
        when /Introduction/i
          introduction bill_event
        when 'Submissions Due'
          committee_details bill_event
        when 'SC Reports'
          committee_report_details bill_event
        when 'Third Reading'
          bill_event.was_split_at_third_reading? ? split_bill_details(bill_event) : ''
        when 'Committee of the whole House: Order of the day for committal discharged'
          'Order of the day for committal discharged.'
        when 'Consideration of report: Order of the day for consideration of report discharged'
          'Order of the day for consideration of report discharged.'
        when 'Second reading: Order of the day for second reading discharged'
          'Order of the day for second reading discharged.'
        when 'First reading: Order of the day for first reading discharged'
          'Order of the day for first reading discharged.'
        else
          ''
      end
    elsif bill_event.has_votes?
      view_bill = bill_event.was_split_at_third_reading? ? split_bill_details(bill_event) : ''
      result = bill_event.result_from_vote self
      result += "<br/><br/>#{view_bill}" unless view_bill.blank?
      result
    else
      result = bill_event.reading_result_from_contributions self

      if result.blank?
        bill_event.result_from_contributions self
      else
        result
      end
    end
  end

app/views/bills/_a_bill.haml
%tr
  %td= bill_type_label(a_bill)
  %td= party_name(a_bill)
  %td= link_to(a_bill.bill_name, bill_url(a_bill))
  %td= a_bill.last_event_name
  %td= a_bill.last_event_date.to_s.gsub('-','/')

app/views/bills/_bill.haml
- key = bill
- bill = bills[key].first
%tr
- if bill
  %td.bill
    %span.bill_name
      = link_to(bill.bill_name, show_bill_url(:bill_url => bill.url))
    %span.royal_assent
      = bill.royal_assent && !@parliament.date_within?(bill.royal_assent) ? "(#{format_date(bill.royal_assent)})" : ''
  %td= bill.member_in_charge.party ? link_to_party(bill.member_in_charge.party) : 'no party '+ bill.member_in_charge.full_name
  %td= bill_type(bill).chomp(' bill')
  - unless bill.divided_into_bills.empty?
    - bill.divided_into_bills.sort_by(&:bill_name).each do |split_bill|
      %tr
        %td.split_bill
          %span.bill_name
            = link_to_bill split_bill
          %span.royal_assent
            = split_bill.royal_assent && !@parliament.date_within?(split_bill.royal_assent) ? "(#{format_date(split_bill.royal_assent)})" : ''
        %td
        %td
- else
  %td= key
  %td
  %td

app/views/bills/_bill_description.haml
- bill = bill_description
#bill_description
  - if bill.description.blank?
    #bill_description
  - else
    %p= bill.description
  - if bill.former_name
    %p
      Formerly named the
      %span.former_name= bill.former_name + '.'
  - if bill.formerly_part_of
    %p
      Formerly part of
      %span.fomerly_part_of= link_to_bill(bill.formerly_part_of) + '.'
  - if bill.divided_into_bills.size > 0
    - bill_was = (bill.divided_into_bills.size == 1) ? 'Bill' : 'Bills';
    %p
      = %Q[#{bill_was} formerly part of this bill:]
      %span.divided_into= bill.divided_into_bills.collect{|b| link_to_bill(b)}.join(', ') + '.'
  %p= submission_alert bill

app/views/bills/_bill_events.haml
#bill_events
  %h2 Bill Events
  %p
  %table.bill-table
    %tbody
    %tr
      %th.debate-column Event
      %th.date Date
      %th.summary
      - if @have_votes
        %th.ayes Ayes
        %th.noes Noes
        %th.abstentions Abstentions
    = render :partial => 'bill_event', :collection => bill_events
  - if @missing_votes
    %p* We don't have voting data from before Nov 2005 in our database at present.

app/views/bills/_bill_group.haml
- key = bill_group
%tr
  %td
    %a{ :name=> prefix+key }
    - unless (prefix+key == prefix+first)
      %span= '&nbsp;'
  %td
  %td
= render :partial => 'bill', :collection => letter_to_bills[key].sort, :locals => {:bills => bills}

app/views/bills/_blog_entry.haml
- entry = blog_entry
.hentry
  .entry-title
    = link_to entry.title, entry.url
  %div
    %span.vcard.author
      = entry.publisher
    %span.published{ :title=> entry.published_date }
      = entry.display_date
  .entry-summary
    = entry.content

app/views/bills/_evidence.haml
- submission = evidence
= link_to_evidence submission

app/views/bills/_tracker_separator.haml
,

app/views/bills/assented.haml
- @title = "Assented Bills: Aotearoa New Zealand's Parliament"
- @description = "Bills assented during 48th and 49th New Zealand Parliaments"
#normalcontent
  %h1 Assented Bills
  .divider3
  .contentarea
    - @parliaments.each do |parliament|
      - @parliament = parliament
      %h2= "Assented during #{parliament.ordinal} Parliament"
      %p
        %span= "Bills that received Royal Assent during the #{parliament.ordinal} Parliament."
        %span.right= %Q[See also: #{ link_to ('Negatived Bills', negatived_url) } | #{ link_to ('Current Bills', bills_url) }]
      - letter_to_assented = @letter_to_assented_by_parliament.assoc(parliament)[1]
      - letters = letter_to_assented.keys.sort
      - bills_assented = @bills_assented_by_parliament.assoc(parliament)[1]
      %p= render(:partial => 'bill_group_link', :collection => letters, :locals => {:prefix => ''})
      %table
        %tr
          %th Bill name
          %th Party of MP in charge
          %th Bill type
        = render(:partial => 'bill_group', :collection => letters, :locals => {:letter_to_bills => letter_to_assented, :bills => bills_assented, :prefix => '', :first => letters[0]})
      .divider3
    .divider3
    %p= %Q[See also: #{ link_to ('Negatived Bills', negatived_url) } | #{ link_to ('Current Bills', bills_url) }]

app/views/bills/index.haml
- @title = "Bills: Aotearoa New Zealand Parliament "
- @description = 'Current bills debated by the 48th New Zealand Parliament'
- @javascript = 'bills_table'
#normalcontent
  %h1 Current Bills
  .divider3
  .contentarea
    %p
      %span= @description
      %span.right
        %span See also:
        = link_to('Assented Bills', assented_bills_url) 
        = link_to('Negatived Bills', negatived_bills_url)
    .yui-skin-sam
      #bills
        %table#bill-table
          %thead
            %tr
              %th Type
              %th#party_of_mp_in_charge= 'Party'
              %th Bill name
              %th Event
              %th Event date
          %tbody
            = render(:partial => 'a_bill', :collection => @bills_current)
    .divider3
    .divider3
    %p See also:
    = link_to('Assented Bills', assented_bills_url) 
    = link_to('Negatived Bills', negatived_bills_url)

app/views/bills/invalid_bill.haml
- @title = %Q[Aotearoa New Zealand Parliament]
%h2 Bill not found

app/views/bills/negatived.haml
- @title = "Bills: Aotearoa New Zealand's Parliament "
#normalcontent
  %h1 Negatived Bills
  .divider3
  .contentarea
    %p
      %span Bills that have been negatived by the 48th Parliament.
      %span.right= %Q[See also: #{link_to ('Current Bills', bills_url) } | #{ link_to ('Assented Bills', assented_url) }]
    %table
      %tr
        %th Bill name
        %th Party of MP in charge
        %th Bill type
      = render(:partial => 'bill_group', :collection => @letter_to_negatived.keys.sort, :locals => {:letter_to_bills => @letter_to_negatived, :bills => @bills_negatived, :prefix => '', :first => @letter_to_negatived.keys.sort[0]})
    .divider3
    .divider3
    %p= %Q[See also: #{ link_to ('Current Bills', bills_url) } | #{ link_to ('Assented Bills', assented_url) }]

app/views/bills/show_bill.haml
- @title = about_title(@bill)
- @description = bill_meta_description(@bill)
- is_production_env = (RAILS_ENV == 'production')
- @javascript = 'feeds' if is_production_env
- @atom = 'show_bill_atom' unless is_production_env
- cache do
  #primarycontainer
    = render :partial => 'bill_description', :object => @bill
    - if @submissions_count > 0
      %p
        There have been
        = link_to "#{@submissions_count} submissions", show_bill_submissions_url(:bill_url => @bill.url)
        on this bill.
    - if @admin
      %p= h @bill.inspect
      - @bill.bill_events.each do |e|
        %p= h e.inspect
    = render :partial => 'bill_events', :object => @top_level_bill_events
    - if is_production_env || true
      = render :partial => 'news_feeds'
- if current_user
  = render :partial => 'bill_tracking'

app/views/bills/show_bill_atom.atom.haml
= %Q|<?xml version="1.0" encoding="UTF-8"?>|
%feed{ "xml:lang".to_sym => "en-NZ", :xmlns=>"http://www.w3.org/2005/Atom" }
  %title= "#{@bill.bill_name} | TheyWorkForYou.co.nz"
  %subtitle= "Track the #{@bill.bill_name}'s progress through New Zealand's Parliament via TheyWorkForYou.co.nz."
  %id= show_bill_uri(@bill)
  %link{:rel=>"alternate", :type=>"text/html", :href=>show_bill_uri(@bill)}
  %link{:rel=>"self", :type=>"application/atom+xml", :href=>"#{show_bill_uri(@bill)}.atom"}
  %author
    %name TheyWorkForYou.co.nz
    %uri http://theyworkforyou.co.nz/

  %rights Creative Commons Attribution-Noncommercial-Share Alike 3.0 New Zealand
  %link{ :rel=>"license", :type=>"application/rdf+xml", :href=>"http://creativecommons.org/licenses/by-nc-sa/3.0/nz/rdf" }
  %updated= @bill_events.empty? ? Time.now : @bill_events.first.created_at.xmlschema

  = @bill_events.each do |bill_event|
    %entry
      %id= bill_event_atom_id bill_event
      %published= bill_event.created_at.xmlschema
      %updated= bill_event.updated_at.xmlschema
      %link{ :type=>"text/html", :rel=>"alternate", :href=>bill_event_url(bill_event) }
      %title= "#{@bill.bill_name}-#{bill_event.name}"
      %content{ :type=>"html" }= h(bill_event_description(bill_event))