config/routes.rb
Twfynz::Application.routes.draw do
  root :to => "application#home"
  match "search" => "application#search"
  match "about" => "application#about"

  resources :bills do
    collection do
      get "assented"
      get "negatived"
    end
  end
  resources :portfolios
  resources :mps do
    collection do
      get "by_first"
      get "by_party"
      get "by_electorate"
      get "contribution_match"
    end
  end

  resources :organisations
  resources :parliaments
  resources :submissions
  resources :trackings
  resources :places, only: :index do
    get ':name' => 'places#show_place', on: :collection
  end

  match "portfolios/:portfolio_url/:year/:month/:day/:url_slug" => "debates#show_portfolio_debate", :as => "show_portfolio_debate"

  resources :debates do
    collection do
      get ":date", to: "debates#show_debates_on_date", as: "on_date"
    end
  end
  resources :parties
  resources :written_questions do
    collection do
      get "by_asker"
      get "by_portfolio"
    end
  end

  match 'users/signup' => 'user#signup', via: [:get, :post]
  post 'users/signup/individual' => 'user#signup_individual'
  post 'users/signup/organisation' => 'user#signup_organisation'
  post 'users/login' => 'user#login'
  get 'users/logout' => 'user#logout'
  get 'users/forgot_password' => 'user#forgot_password'
  get 'users/change_password' => 'user#change_password'
  get 'user/:user_name' => 'user#user_home'

end

app/models/user.rb
# encoding: UTF-8
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  type            :string(255)
#  login           :string(255)
#  hashed_password :string(255)
#  email           :string(255)
#  salt            :string(255)
#  blog_url        :string(255)
#  site_url        :string(255)
#  email_confirmed :boolean
#  created_at      :datetime
#  updated_at      :datetime
#

require 'digest/sha1'
require 'rubygems'

class User < ActiveRecord::Base

  validates_length_of :login, :within => 3..40
  validates_length_of :password, :within => 6..40

  validates_presence_of :login, :email, :password, :password_confirmation, :salt
  validates_uniqueness_of :login, :email
  validates_uniqueness_of :blog_url, :allow_nil => true, :if => Proc.new { |u| !u.blog_url.blank? }
  validates_format_of :blog_url, :with => /^((?:[-a-z0-9]+\.)+[a-z]{2,})$/, :allow_nil => true, :if => Proc.new { |u| !u.blog_url.blank? }
  validates_confirmation_of :password

  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/,
      :if => Proc.new { |u| !u.email.blank? },
      :message => "format is invalid"

  validates_format_of :login, :with => /^([a-z0-9]+)(_[a-z]0-9+)*$/,
      :if => Proc.new { |u| !u.login.blank? },
      :message => "format is invalid, try lower case letters, with _ in between words"

  attr_protected :id, :salt

  attr_accessor :password, :password_confirmation

  #has_many_polymorphs :items, :from => [:bills, :portfolios, :committees], :through => :trackings

  def self.authenticate(login, pass)
    user = find(:first, :conditions=>["login = ?", login])
    if (not(user.nil?) and (User.encrypt(pass, user.salt) == user.hashed_password))
      user
    else
      nil
    end
  end

  def tracked_items
    items(true)
  end

  def password=(pass)
    @password=pass
    self.salt = User.random_string(10) unless self.salt
    self.hashed_password = User.encrypt(@password, self.salt)
  end

  def send_new_password
    new_pass = User.random_string(10)
    self.password = self.password_confirmation = new_pass
    self.save
    User.deliver_forgot_password(self.email, self.login, new_pass)
  end

  def self.deliver_forgot_password(email, login, new_pass)

  end

  protected

    def self.encrypt(pass, salt)
      Digest::SHA1.hexdigest(pass + salt)
    end

    def self.random_string(len)
      # generate a random password consisting of strings and digits
      chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
      newpass = ""
      1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
      return newpass
    end

end

app/controllers/user_controller.rb
#encoding: utf-8
class UserController < ApplicationController

  before_filter :logged_in, :only=>['change_password', 'hidden']

  layout "user_layout"

  def signup
    if request.post?
      user_type = params[:user_type]

      if user_type == 'individual'
        redirect_to :action => 'signup_individual'
      elsif user_type == 'organisation'
        redirect_to :action => 'signup_organisation'
      end
    end
  end

  def signup_individual
    @user = User.new(params[:user]) #shouldn't there be more params used here?
    if request.post?
      if @user.save
        session[:user] = User.authenticate(@user.login, @user.password)
        flash[:message] = "Signup successful"
        redirect_to :action => "user_home", :user_name => @user.login
      else
        flash[:warning] = "Signup unsuccessful"
        render :template => 'user/signup_individual'
      end
    elsif current_user
      @user = current_user
      redirect_to :action => "user_home", :user_name => @user.login
    end
  end

  def login
    if request.post?
      if (session[:user] = User.authenticate(params[:user][:login], params[:user][:password]) )
        flash[:message]  = "Login successful"
        redirect_to_stored
      else
        flash[:warning] = "Login unsuccessful"
      end
    elsif current_user
      @user = current_user
      redirect_to :action => "user_home", :user_name => @user.login
    end
  end

  def logout
    session[:user] = nil
    flash[:message] = 'Logged out'
    redirect_to :controller => 'application', :action => 'home'
  end

  def forgot_password
    if request.post?
      user = User.find_by_email(params[:user][:email])
      if user and user.send_new_password
        flash[:message]  = "A new password has been sent by email."
        redirect_to :action=>'login'
      else
        flash[:warning]  = "Couldn't send password"
      end
    end
  end

  def change_password
    @user = session[:user]
    if request.post?
      @user.update_attributes(:password => params[:user][:password],
          :password_confirmation => params[:user][:password_confirmation])
      if @user.save
        flash[:message]="Password changed"
      end
    end
  end

  def user_home
    @user_name = params[:user_name]

    if (current_user and current_user.login == @user_name)
      @tracked_items = current_user.tracked_items
      respond_to do |format|
        format.html { render :template => 'user/user_home' }
        format.atom { render :template => 'user/user_home.atom.haml', :layout => false }
      end
    elsif (user = User.find_by_login(@user_name))
      @tracked_items = user.tracked_items

      respond_to do |format|
        format.html { render :template => 'user/other_user_home' }
        format.atom { render :template => 'user/user_home.atom.haml', :layout => false }
      end
    else
      render :template => 'user/user_not_found'
    end
  end

  def hidden
  end

  def delete

  end

  def edit

  end

end

app/helpers/user_helper.rb
# encoding: UTF-8
module UserHelper
end

app/views/user/_tracked_item.haml
%tr
  - debates_in_groups_by_name, votes_by_name = tracked_item.debates_by_name_names_votes_by_name
  - bill_events = tracked_item.bill_events
  - bill_event = bill_events.last
  - date = bill_event.date
  - name = bill_event.name
  - debates = debates_in_groups_by_name.blank? ? nil : debates_in_groups_by_name.select {|list| list.first.normalized_name == name}.flatten
  - debates = nil if debates.blank?
  - votes = votes_by_name.blank? ? nil : votes_by_name[name]
  %td.item_name= link_to_bill(tracked_item)
  %td= debate_name name, debates
  %td.date= debate_last_date date, debates
  %td= tracked_item_list tracked_item

app/views/user/_tracked_items.haml
- @javascript = 'trackings_table'
#trackings
  %table#items_tracked
    %thead
      %th.item_name Name
      %th Recent event
      %th.date Event date
      %th Others tracking
    %tbody
      = render :partial => 'tracked_item', :collection => tracked_items

app/views/user/change_password.haml
- @title = 'User change password'
= error_messages_for 'user'
- form_tag(:action=> "change_password") do
  %label{ :for=>"user_password" } Choose password:
  %br
  = password_field "user", "password", :size => 20, :value=>""
  %br
  %label{ :for=>"user_password_confirmation" } Confirm password:
  %br
  = password_field "user", "password_confirmation", :size => 20, :value=>""
  %br
  %p= submit_tag 'Submit'

app/views/user/forgot_password.haml
- @title = 'User forgot password'
- form_tag(:action=> "forgot_password") do
  %h1 Forgotten your password?
  %p To reset your password, please enter the email address you have registered with.
  %table.password
    %tbody
      %tr
        %td
          %label{ :for=>"user_email" } Email:
        %td
          = text_field "user","email"
      %tr
        %td
        %td
          %span= submit_tag 'Email password'

app/views/user/login.haml
- @title = 'User login'
- @login_on = true
- @script = "Event.observe(window, 'load', function() { $('user_login').focus(); } );"
- form_tag(:action=> "login") do
  %h1 Welcome to TheyWorkForYou.co.nz
  = error_messages_for 'user'
  %table.login
    %tbody
      %tr
        %td
          %label{ :for=>"user_login" } Username:
        %td
          = text_field "user", "login", :size => 20
        %td
      %tr
        %td
          %label{ :for=>"user_password" } Password:
        %td
          = password_field "user", "password", :size => 20
        %td
      %tr
        %td
        %td
          %span#login= submit_tag "Login"
        %td
          %span.shift-right= link_to 'Forgotten password?', :action => 'forgot_password'
  %p
    Login above or
    =link_to('sign up now for free', :action => 'signup') + '.'

app/views/user/login_required_message.haml
You must log in to track

app/views/user/other_user_home.haml
- @title = @user_name + "'s page"
%h1= @title
- if @tracked_items.size > 0
  %h2= %Q[Items #{@user_name} is tracking]
  = render :partial => 'tracked_items', :object => @tracked_items
- else
  %p
    Items you track will be listed here.

app/views/user/signup.haml
- @title = 'User signup'
- individual_submit_id = 'individual_submit'
- @script = "Event.observe(window, 'load', function() { if ($('#{individual_submit_id}')) $('#{individual_submit_id}').focus(); } );"
%h1 Join us in tracking NZ's Parliament
#individual_signup
  - form_tag(:action => 'signup') do
    = hidden_field_tag(:user_type, 'individual')
    %span.user_type= submit_tag("I'm signing up as an individual", :id => individual_submit_id)
#organisation_signup
  - form_tag(:action => 'signup') do
    = hidden_field_tag(:user_type, 'organisation')
    %span.user_type= submit_tag "I'm signing up my organisation"

app/views/user/signup_individual.haml
- @title = 'User signup'
- @script = "Event.observe(window, 'load', function() { if ($('user_login')) $('user_login').focus(); } );"
%h1 Your details
- if flash[:warning]
  %p= flash[:warning]
= error_messages_for('user').sub('<ul>', '<ul class="linklist">')
- form_tag(:action=> "signup_individual") do
  %table.signup
    %tbody
      %tr
        %td
          %label{ :for=>"user_login" } Username *
        %td
          = text_field("user", "login", :size => 20)
        %td
          %p We recommend you don't use your real name.
          %p Use lower case letters, separated by '_'.
          %p This will be your public user name.
          %p Minium 3 characters long.
      %tr
        %td
          %label{ :for=>"user_password" } Password *
        %td
          = password_field "user", "password", :size => 20
        %td
          %p Minium 6 characters long.
      %tr
        %td
          %label{ :for=>"user_password_confirmation" } Confirm password *
        %td
          = password_field "user", "password_confirmation", :size => 20
        %td
      %tr
        %td
          %label{ :for=>"user_email" } Email *
        %td
          = text_field "user", "email",  :size => 20
        %td
          %p Used if you forget your password.
          %p Won't be public.
      %tr
        %td
          %label{ :for=>"user_blog_url" } Blog URL
        %td
          http://
          = text_field "user", "blog_url", :size => 14
        %td
          %p Optional.
          %p Will be public on the site.
          %p Will be added to our blog search whitelist.
      %tr
        %td
          %p * compulsory
        %td
          %span#signup= submit_tag "Sign up as an individual"
        %td

app/views/user/signup_organisation.haml
- @title = 'Organisation signup'
%h1 Your organisation's details
- form_tag(:action=> "signup_organisation") do
  = error_messages_for('organisation').sub('<ul>', '<ul class="linklist">')
  %table.signup
    %tbody
      %tr
        %td
          %label{ :for=>"organisation_site_url" } Organisation URL *
        %td
          http://
          = text_field "organisation", "site_url", :size => 14
        %td
          %p Will be public on the site.
          %p Will be used to create login name.
      %tr
        %td
          %label{ :for=>"organisation_email" } Email *
        %td
          = text_field "organisation", "email",  :size => 20
        %td
          %p Must be at domain of your website.
          %p Used if you forget your password.
          %p Won't be public.
      %tr
        %td
          %label{ :for=>"organisation_password" } Password *
        %td
          = password_field "organisation", "password", :size => 20
        %td
          %p Minium 6 characters long.
      %tr
        %td
          %label{ :for=>"organisation_password_confirmation" } Confirm password *
        %td
          = password_field "organisation", "password_confirmation", :size => 20
        %td
      %tr
        %td
          %label{ :for=>"organisation_blog_url" } Organisation blog or news URL
        %td
          http://
          = text_field "organisation", "blog_url", :size => 14
        %td
          %p Optional.
          %p Will be public on the site.
          %p Will be added to our blog search whitelist.
      %tr
        %td
          %p * compulsory
        %td
          %span#signup= submit_tag "Sign up your organisation"
        %td

app/views/user/user_home.atom.haml
= '<?xml version="1.0" encoding="UTF-8"?>'
%feed{ 'xml:lang'.to_sym => "en-NZ", :xmlns => "http://www.w3.org/2005/Atom" }
  %id= 'tag:localhost:people'
  %link{ :type=>"application/atom+xml", :rel=>"self", :href=>"http://example.com/people.atom" }
  %title Items tracked
  %updated
  - @tracked_items.reverse.each do |tracked_item|
    - debates_in_groups_by_name, votes_by_name = tracked_item.debates_by_name_names_votes_by_name
    - events_by_date = tracked_item.bill_events
    - bill_event = events_by_date.last
    - date = bill_event.date
    - name = bill_event.name
    - debates = debates_in_groups_by_name.blank? ? nil : debates_in_groups_by_name.select {|list| list.first.normalized_name == name}.flatten
    - debates = nil if debates.blank?
    - votes = votes_by_name.blank? ? nil : votes_by_name[name]
    %entry
      %id= "tag:twfy,2007-05-18T16:35:00-07:00:#{tracked_item.class.name}#{tracked_item.id.to_s}"
      %updated= (debates) ? debates.first.date.xmlschema : tracked_item.last_event[0]
      - link = (debates) ? get_url(debates.first) : show_bill_url(:bill_url => tracked_item.url)
      %link{ :type => "text/html", :rel => "alternate", :href => link }
      %title= tracked_item.bill_name
      %content{ :type=>"html" }= debate_name name, debates
      %author
        %name TheyWorkForYou.co.nz
        %email support@theyworkforyou.co.nz

app/views/user/user_home.haml
- @title = 'Welcome ' + @user_name
%h1= @title
- if @tracked_items.size > 0
  %h2 Items you are tracking
  = render :partial => 'tracked_items', :object => @tracked_items
- else
  %p
    Items you track will be listed here.

app/views/user/user_not_found.haml
- @title = 'User not found'
%h1= @title
%p No user exists with this name.