config/routes.rb
Twfynz::Application.routes.draw do
  root :to => "application#home"
  match "search" => "application#search"
  match "about" => "application#about"

  resources :bills do
    collection do
      get "assented"
      get "negatived"
    end
  end
  resources :portfolios
  resources :mps do
    collection do
      get "by_first"
      get "by_party"
      get "by_electorate"
      get "contribution_match"
    end
  end

  resources :organisations
  resources :parliaments
  resources :submissions
  resources :trackings
  resources :places, only: :index do
    get ':name' => 'places#show_place', on: :collection
  end

  match "portfolios/:portfolio_url/:year/:month/:day/:url_slug" => "debates#show_portfolio_debate", :as => "show_portfolio_debate"

  resources :debates do
    collection do
      get ":date", to: "debates#show_debates_on_date", as: "on_date"
    end
  end
  resources :parties
  resources :written_questions do
    collection do
      get "by_asker"
      get "by_portfolio"
    end
  end

  match 'users/signup' => 'user#signup', via: [:get, :post]
  post 'users/signup/individual' => 'user#signup_individual'
  post 'users/signup/organisation' => 'user#signup_organisation'
  post 'users/login' => 'user#login'
  get 'users/logout' => 'user#logout'
  get 'users/forgot_password' => 'user#forgot_password'
  get 'users/change_password' => 'user#change_password'
  get 'user/:user_name' => 'user#user_home'

end

app/controllers/places_controller.rb
# encoding: UTF-8
class PlacesController < ApplicationController

  def index
    @places = Geoname.find_all_places
  end

  def show_place
    name = params[:name]
    @place = Geoname.find_by_slug(name)
    zoom = @place.feature_code == 'PPLX' ? 11 : 7
    @map = make_map [[@place,[]]], @place.latitude, @place.longitude, zoom
    @contribution_in_groups_by_debate = @place.find_mentions
  end
end

app/helpers/places_helper.rb
# encoding: UTF-8
module PlacesHelper

end

app/views/places/index.haml
- @javascript = 'places_table'
- @title = "Places in Aotearoa New Zealand"
%h1 Places in Aotearoa New Zealand
%p
  We have identified
  = @places.size
  places that have been mentioned in debates since November 2005.
  This list may be incomplete. Please email any feedback about this list to:
  %br
  %img{ :alt=>"rob at they work for you dot co dot nz", :class=>"link", :src=>"images/e.png" }
#places
  %table.place-table
    %thead
      %tr
        %th Place
        %th Population
        %th Mentions in debates
    %tbody
      - @places.each do |place|
        %tr
          %td= link_to place.name, show_place_url(:name => place.slug)
          %td.number= place.population
          %td.number= place.count_of_mentions

app/views/places/show_place.haml
- @title = "#{@place.name}, Aotearoa New Zealand"
- # @javascript = 'portfolios_table'
- count = @place.count_of_mentions
#place
  %h1
    = @place.name
  %p
    A
    = link_to('place in Aotearoa New Zealand', places_url())
    that has been mentioned in
    = link_to "#{count} parliamentary #{count == 1 ? 'debate' : 'debates'}", '#mentions'
    since November 2005.
  - if @map
    = @map.div(:width => 360, :height => 360)
  %p
    The latitude, longitude
    = link_to "data for #{@place.name}", "http://www.geonames.org/#{@place.geonameid}/"
    is provided by the
    = link_to ('GeoNames geographical database', 'http://www.geonames.org/')
    under a
    = link_to('Creative Commons Attribution 3.0 License', 'http://creativecommons.org/licenses/by/3.0/', :rel=>"license")+'.'
#mentions
  = render :partial => 'mentions/contribution_groups', :collection => @contribution_in_groups_by_debate, :locals => { :terms => @place.name }